name: Windows Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'
          architecture: 'x64'
      - name: Build
        run: |
          pip install -r requirements.txt
          pyinstaller -F ./main.py -n quiz.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/quiz.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}